const inquirer = require('inquirer');
const axios = require('axios');

const { getConfig } = require('../lib/config');

/**
 * get list of report in ezunpaywall
 * @param {Stringng} ezunpaywall - ezunpaywallURL
 * @returns {array<string>} array of name of report
 */
const getReports = async (ezunpaywall) => {
  let res;

  try {
    res = await axios({
      method: 'GET',
      url: `${ezunpaywall}/update/snapshot`,
    });
  } catch (err) {
    console.error(`service unavailable ${ezunpaywall}`);
    process.exit(1);
  }

  return res?.data;
};

/**
 * get the content of report
 *
 * @param {string} option.file -f --file - report file installed on ezunpaywall
 * @param {boolean} option.list -l --list - list of reports generated by ezunpaywall
 * @param {boolean} option.latest -la --latest [latest]
 * @param {string} option.status -s --status <status> - status of report,
 * success and error only accepted
 * @param {boolean} option.use -u --use <use> - pathfile of custom config
 */
const report = async (option) => {
  const config = await getConfig(option.use);

  const ezunpaywallURL = `${config.ezunpaywall.protocol}://${config.ezunpaywall.host}:${config.ezunpaywall.port}`;

  // check list and latest, file,
  if (option.list && option.latest) {
    console.error('option --latest is impossible to use with --list');
    process.exit(1);
  }
  if (option.list && option.file) {
    console.error('option --file is impossible to use with --list');
    process.exit(1);
  }

  // check file and latest, status
  if (option.file && option.latest) {
    console.error('option --latest is impossible to use with --file');
    process.exit(1);
  }
  if (option.file && option.status) {
    console.error('option --status is impossible to use with --file');
    process.exit(1);
  }
  if (option.status) {
    if (option.status !== 'error' && option.status !== 'success') {
      console.error('option --status only use <error> or <success>');
      process.exit(1);
    }
  }

  let res1;
  let url = '';
  let query = {};

  if (!option.status && !option.latest) query = null;
  if (option.status) query.status = option.status;

  if (option.list) {
    const reports = await getReports(ezunpaywallURL);
    if (!reports?.length) {
      console.log('no reports available');
      process.exit(0);
    }
    const oneReport = await inquirer.prompt([{
      type: 'list',
      pageSize: 5,
      name: 'files',
      choices: reports,
      message: 'files',
      default: reports.slice(),
      source: (answersSoFar, input) => new Promise((resolve) => {
        const result = reports?.data
          .filter((file) => file.toLowerCase().includes(input.toLowerCase()));
        resolve(result);
      }),
    }]);
    option.file = oneReport.files;
  }

  if (option.file) url += `/${option.file}`;
  if (option.latest) query.latest = option.latest;

  try {
    res1 = await axios({
      method: 'get',
      url: `${ezunpaywallURL}/update/report${url}`,
      params: query,
    });
  } catch (err) {
    if (res1?.response?.status === 404) {
      console.error('file does not exist');
      process.exit(1);
    }
    console.error(`service unavailable ${config.url}:${config.port}`);
    process.exit(1);
  }
  console.log(JSON.stringify(res1.data, null, 2));
};

module.exports = {
  report,
};
